TAG: "ADE"

TASK: "offline"

SEED: 13

DATA: 
  ROOT: "../data/ADEChallengeData2016"
  BATCH_SIZE: 12 # per each GPU
  CROP_SIZE: 512
  
MODEL:
  WEIGHTS: "resnet101-63fe2227.pth" 
  SYNC_BN: True
  FREEZE_LIST: []
  MIB_CLS_INIT: False

LOSS:
  CE:
    TYPE: "ce"

SOLVER:
  LR: 1e-2 
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 1e-4
  MAX_EPOCH: 60 
  GAMMA: 0.9
