TAG: "ALIFE-M-S3"

TASK: "'50'"
STEP: 2 
OVERLAP: True

SEED: 28200 

DATA: 
  ROOT: "../data/ADEChallengeData2016"
  BATCH_SIZE: 12 # for each GPU
  CROP_SIZE: 512

MODEL:
  WEIGHTS: "ALIFE-M-S1_28200_ov_50_2_last.pt"
  SYNC_BN: True
  FREEZE_TYPE: "step3"
  MIB_CLS_INIT: False

LOSS:
  CE: 
    TYPE: "fl"
  MY:
    WEIGHT: 0.
  MEMORY:
    TYPE: "ce"
    WEIGHT: .5 

SOLVER:
  LR: 1e-3
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 1e-4
  MAX_EPOCH: 1 
  GAMMA: 0.9
